docker build script and runner-action

diff --git a/.github/workflows/container-build-push.yaml b/.github/workflows/container-build-push.yaml
--- a/.github/workflows/container-build-push.yaml
+++ b/.github/workflows/container-build-push.yaml
@@ -22,6 +22,8 @@ jobs:
   build-and-push-image:
     runs-on: cfa-cdcgov
     name: Build and push image
+    outputs:
+        tag: ${{ steps.image-tag.outputs.tag }}
 
     steps:
       - name: Login to Azure
@@ -52,12 +54,46 @@ jobs:
             echo "tag=${{ steps.branch-name.outputs.branch }}" >> $GITHUB_OUTPUT
           fi
 
-      - name: Build and push the container image
-        id: build_and_push_model_image
-        uses: docker/build-push-action@v6
+      - name: Docker Login
+        uses: docker/login-action@v3
         with:
-          no-cache: true
-          push: true
-          tags: |
-            ${{ vars.CONTAINER_REGISTRY_URL}}/${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}
-          file: Containerfile
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Docker build and push
+        run: |
+          chmod +x $GITHUB_WORKSPACE/.github/scripts/docker_build_and_push.sh
+          $GITHUB_WORKSPACE/.github/scripts/docker_build_and_push.sh ${{ env.IMAGE_NAME }} ${{ steps.image-tag.outputs.tag }}
+  
+  acr-import:
+    needs: build-pipeline-image
+    name: Import image from GHCR
+    runs-on: ubuntu-latest
+    
+    steps:
+    - name: ACR Import
+      uses: CDCgov/cfa-actions/runner-action@v1.3.0
+      with:
+        github_app_id: ${{ secrets.REPO_CDCENT_ACTOR_APP_ID }}
+        github_app_pem: ${{ secrets.REPO_CDCENT_ACTOR_APP_PEM }}
+        wait_for_completion: true
+        print_logs: true
+        script: |
+          IMAGE_TAG=${{ env.IMAGE_NAME }}:${{ needs.build-and-push-image.outputs.tag }}
+
+          az login --service-principal \
+          --username ${{ fromJSON(secrets.EDAV_STF_SERVICE_PRINCIPAL).clientId }} \
+          --password ${{ fromJSON(secrets.EDAV_STF_SERVICE_PRINCIPAL).clientSecret }} \
+          --tenant ${{ fromJSON(secrets.EDAV_STF_SERVICE_PRINCIPAL).tenantId }}
+
+          az acr import --name ${{ vars.CONTAINER_REGISTRY_URL }} \
+            --source "ghcr.io/cdcgov/$IMAGE_TAG" \
+            --username '${{ github.repository_owner }}'\
+            --password ${{ secrets.GITHUB_TOKEN }} \
+            --image "$IMAGE_TAG" \
+            --force && echo 'Copied image!'
+
+          if [ $? -ne 0 ]; then
+            echo "Failed to copy image"
+          fi  
